### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy2stl'

### ISSUE THREAD

**Issue by PatrickM84** [thearn/stl_tools#8]
Hello,

I followed your instructions but when i try to use image2stl in command line i get the following error:
Im using Linux Mint 18.2

image2stl leen.png 
Traceback (most recent call last):
  File "/usr/local/bin/image2stl", line 11, in <module>
    load_entry_point('stl-tools==0.3.0', 'console_scripts', 'image2stl')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/stl_tools/image2stl.py", line 4, in <module>
    from numpy2stl import numpy2stl
ModuleNotFoundError: No module named 'numpy2stl'

Any ideas how i can repair this? - Google does not know this error

**Comment by jlobie** [comment]
Hi, I run into the same issue while trying stl_tools on a current python windows environment.
Did you find a solution/workaround?
Jens

**Comment by catskul** [comment]
Looks like the import should be  `from stl_tools.numpy2stl import numpy2stl` editing it does the trick. Made a PR #14 but there are PRs in queue from several years ago so not sure how likely it is to be merged.
